name: Code Linter

on:
  push:
  pull_request:


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup build -Dwith_tests=true
    - run: meson test -C build -v
    - run: cppcheck --project=build/compile_commands.json
